### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by ktdreyer** [SUSE/lrbd#2]
Would you mind tagging releases in Git? Just a simple annotated tag is fine, like `1.0.2` or `1.0.3`.

**Comment by swiftgist** [comment]
On Thursday, February 11, 2016 12:50:31 PM Ken Dreyer wrote:

> Would you mind tagging releases in Git? Just a simple annotated tag is fine,
> like `1.0.2` or `1.0.3`.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SUSE/lrbd/issues/2
> Hi Ken,
>   I have been.  From branch 1.0,  git tag shows

0.9.1
0.9.10
0.9.2
0.9.3
0.9.4
0.9.5
0.9.6
0.9.7
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3

  What do you see?

Eric

**Comment by ktdreyer** [comment]
Thanks Eric, would you mind pushing them to GitHub?

`git push --tags`

**Comment by swiftgist** [comment]
On Thursday, February 11, 2016 02:17:41 PM Ken Dreyer wrote:

> Thanks Eric, would you mind pushing them to GitHub?
> 
> `git push --tags`
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SUSE/lrbd/issues/2#issuecomment-183082157
> Done.  Sorry about that... forget that tags do not push by default.

Eric

**Comment by ktdreyer** [comment]
Thanks, I see the tags now!
