### ISSUE TITLE
"Disable restart of service during future updates" is not in master

### ISSUE THREAD

**Issue by ktdreyer** [SUSE/lrbd#4]
The "Disable restart of service during future updates" commit (73854589471b290bb351719a553af21b9febdca9) is in the `1.0` branch, but it's not in master.

It's typical to have all changes go to the master branch first, and then cherry-pick the specific ones that you want to the stable release branches.

Would you mind cherry-picking that one to master?

**Comment by swiftgist** [comment]
Hi Ken,
  I pushed it to master.  I had a few changes pending, but pushed this by itself.  Considering the macros in the spec file, I do not know if these are SUSE specific or if they work fine on RedHat/Fedora.
