### ISSUE TITLE
"git describe" on master is older than on "1.0" branch

### ISSUE THREAD

**Issue by ktdreyer** [SUSE/lrbd#5]
Would you mind tagging the tip of the master branch? Maybe you could tag it as "1.1.0" or something?

Currently "`git describe master`" prints "1.0.2", whereas "`git describe 1.0`" prints "1.0.4", which is confusing.

**Comment by ktdreyer** [comment]
CC @mikechristie since we recently discussed this via email

**Comment by swiftgist** [comment]
I added "1.1" thinking that "1.1.0" will be the branch eventually.

**Comment by ktdreyer** [comment]
Thanks for adding a `1.1` tag.

Now the lrbd.spec's `Version:` field still says "1.0.4" :)

Maybe it would be good to write a text file describing the release process, so it's the same every time.

**Comment by swiftgist** [comment]
On Tuesday, March 15, 2016 05:56:46 AM Ken Dreyer wrote:

> Thanks for adding a `1.1` tag.
> 
> Now the lrbd.spec's `Version:` field still says "1.0.4" :)
> 
> Maybe it would be good to write a text file describing the release process,
> so it's the same every time.
> 
> ---
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/SUSE/lrbd/issues/5#issuecomment-196805874

Just pushed changes and an update to the spec file.  

I haven't found a way to automate the versioning with the constraints I have 
for OBS.  Normally building the rpm will catch it for me, but I was wrapping 
up these last changes and haven't created an rpm yet.

Let me know if you have any feedback from the changes in the README.new.
