### ISSUE TITLE
"make tests" fails on master

### ISSUE THREAD

**Issue by ktdreyer** [SUSE/lrbd#6]
Some of the changes in commit f5407a726f3d9cab6f019ad40b5638dac18158a7 caused `make tests` to no longer work properly.

**Comment by ktdreyer** [comment]
cc @mikechristie since he's been looking at this codebase recently

**Comment by swiftgist** [comment]
I have a few other requests and correcting unit tests now.  Are you adding this to your automated builds?

**Comment by ktdreyer** [comment]
We do run `make tests` as part of the lrbd RPM build process in Fedora (although it's not 100% automated to the point of running on every upstream Git commit.)

The reason I noticed this issue was that Mike and I were working on packaging the tip of master, so that we could use the very latest bits.

**Comment by swiftgist** [comment]
Tests are working.  Closing.
